name: "OpenEMS Backend"
version: "2025.9.0"
slug: "openems-backend"
description: "Run OpenEMS Backend inside Home Assistant"
arch:
  - amd64
  - aarch64
startup: "services"
init: false
ports:
  8080/tcp: 8079
  8081/tcp: 8081
  8082/tcp: 8082  
map:
  - type: config
    read_only: false
  - type: ssl
  - type: addons
    read_only: false
  - type: share
    read_only: false
image: openems/backend