#!/usr/bin/with-contenv bash
# shellcheck shell=bash

OPTS = ""

if [[ "$OPENEMS_IPV4_ONLY" =~ ^(true|1|yes|y)$ ]]; then
    OPTS = "$OPTS -java.net.preferIPv4Stack=true"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8079" \
        s6-setuidgid abc \
             /usr/bin/java \
                -Dosgi.clean=true \
                -Dorg.apache.felix.eventadmin.Timeout=0 \
                -Dorg.apache.felix.http.host="::" \
                -Dorg.apache.felix.http.port=8079 \
                -Dfelix.cm.dir=/var/opt/openems/config \
                -Dopenems.data.dir=/var/opt/openems/data \
                -XX:+ExitOnOutOfMemoryError \
                -XX:+UseZGC -XX:+ZGenerational \
                $OPTS \
                -jar /opt/openems/openems-backend.jar
