#!/usr/bin/with-contenv bash
# shellcheck shell=bash

OPTS=""

if [[ "${OPENEMS_IPV4_ONLY^^}" =~ ^(TRUE|1|YES|Y)$ ]]; then
    echo "Run OpenEMS IPv4-Only"
    OPTS="${OPTS} -java.net.preferIPv4Stack=true"
fi

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 8079" \
        s6-setuidgid abc \
             /usr/bin/java \
                -Dosgi.clean=true \
                -Dorg.apache.felix.eventadmin.Timeout=0 \
                -Dorg.apache.felix.http.host="0.0.0.0" \
                -Dorg.apache.felix.http.port=8079 \
                -Dfelix.cm.dir=/var/opt/openems/config \
                -Dopenems.data.dir=/var/opt/openems/data \
                -XX:+ExitOnOutOfMemoryError \
                -XX:+UseZGC -XX:+ZGenerational \
                ${OPTS} \
                -jar /opt/openems/openems-backend.jar
