#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy default config files if they don't exist
cp -nrv /defaults/nginx/* etc/nginx/

# generate template configs
find /etc/nginx/site-templates -type f -name "*.conf.template" -exec ./convert.sh {} \;

# copy pre-generated dhparams or generate if needed
if [[ ! -f /etc/nginx/dhparams.pem ]]; then
    cp /defaults/nginx/dhparams.pem.sample /etc/nginx/dhparams.pem
fi
if ! grep -q 'PARAMETERS' "/etc/nginx/dhparams.pem"; then
    curl -o /etc/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi
