#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy default config files if they don't exist
if [[ ! -f /etc/nginx/openems-nginx.conf ]]; then
    cp /defaults/nginx/openems-nginx.conf.sample /etc/nginx/openems-nginx.conf
fi

if [[ ! -f /etc/nginx/ssl.conf ]]; then
    cp /defaults/nginx/ssl.conf.sample /etc/nginx/ssl.conf
fi

# generate template configs
find /root/nginx-test/site-templates -type f -name "*.conf.template" -exec ./convert.sh {} \;

# copy pre-generated dhparams or generate if needed
if [[ ! -f /etc/nginx/dhparams.pem ]]; then
    cp /defaults/nginx/dhparams.pem.sample /etc/nginx/dhparams.pem
fi
if ! grep -q 'PARAMETERS' "/etc/nginx/dhparams.pem"; then
    curl -o /etc/nginx/dhparams.pem -L "https://ssl-config.mozilla.org/ffdhe4096.txt"
fi
