name: Build OpenEMS-Develop
on:
  push:
    branches:
      - develop

jobs:
  build-java:     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          cache-read-only: false

      - name: Build all Java packages
        run: ./gradlew build

      - name: Resolve OpenEMS bundles
        run: ./gradlew resolve

      - name: Validate BackendApp.bndrun
        run: git diff --exit-code io.openems.backend.application/BackendApp.bndrun

      - name: Validate EdgeApp.bndrun
        run: git diff --exit-code io.openems.edge.application/EdgeApp.bndrun

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Build OpenEMS UI
        run: |
          cd ui
          npm ci --prefer-offline --cache .npm
          node_modules/.bin/ng config cli.cache.path .ng
          node_modules/.bin/ng build -c "openems,openems-edge-prod,prod"
          node_modules/.bin/ng lint
          export CHROME_BIN=/usr/bin/google-chrome-stable
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  report:
    runs-on: ubuntu-latest
    needs: [build-java]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          cache-read-only: false

      - name: Generate JaCoCo Code-coverage-report
        run: ./gradlew test jacocoTestReport --build-cache
        
      - name: Generate JaCoCo Report
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: "io.openems.*/generated/reports/jacoco/**/*.csv"
          generate-summary: true