name: Comment Pull_Request
on:
  workflow_run:
    workflows: [Build OpenEMS]
    types:
      - completed

jobs:
  comment_jacoco:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        run: |
          run_id=$(gh workflow run ${{ github.repository }} -f "Build OpenEMS" --json id | jq -r '.[0]')
          artifact_id=$(gh run view $run_id -j artifacts --json id,name | jq -r '.artifacts[] | select(.name == "jacoco_report") | .id')
          gh run download-artifact $artifact_id --unzip

      - name: 'Comment on PR'
        run: |
          comment=$(cat ./jacoco_report_badge)
          issue_number=$(cat ./jacoco_report_number)
          gh issue comment $issue_number -b "$comment"