name: Develop Build
on:
  push:
    branches:
      - develop

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          cache-read-only: false

      - name: Build Javadocs
        run: ./gradlew buildAggregatedJavadocs --continue

      - name: Build Antora-docs for openems.io
        run: ./gradlew buildAntoraDocs --continue

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS }}
          external_repository: OpenEMS/openems.io
          publish_branch: master
          publish_dir: build/www
          
  build-java:     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
          cache-read-only: false

      - name: Build all Java packages
        run: ./gradlew build test --rerun-tasks
         
      - name: Build JaCoCo Code-coverage-report
        run: ./gradlew jacocoTestReport
        
      - name: Summarize JaCoCo Report
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: "io.openems.*/generated/reports/jacoco/**/*.csv"
          generate-summary: true

  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
          cache-dependency-path: ui/package-lock.json

      - name: Build OpenEMS UI
        run: |
          cd ui
          npm ci --prefer-offline --cache .npm
          node_modules/.bin/ng config cli.cache.path .ng
          node_modules/.bin/ng build -c "openems,openems-edge-prod,prod"
          node_modules/.bin/ng lint
          export CHROME_BIN=/usr/bin/google-chrome-stable
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI