name: Develop Build
on:
  push:
    branches:
      - develop

env:
  JAVA_DISTRIBUTION: "temurin"
  JAVA_VERSION: "17"

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ env.JAVA_DISTRIBUTION}}-${{ env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          distribution:  ${{ env.JAVA_DISTRIBUTION}}
          java-version:  ${{ env.JAVA_VERSION}}
          cache: gradle

      - name: Build Javadocs
        run: ./gradlew buildAggregatedJavadocs --continue
  
      - name: Build Antora-docs for openems.io
        run: ./gradlew buildAntoraDocs --continue
  
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DOCS }}
          external_repository: OpenEMS/openems.io
          publish_branch: master
          publish_dir: build/www