name: Build OpenEMS Docker Image

on:
  push:
    branches:
      - main
      - 'workflow/**'
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [edge, backend, edge-ui, backend-ui]
        include:
          - image: edge
            dockerfile: tools/docker/edge/openems/Dockerfile
            repo: openems/edge
          - image: edge-ui
            dockerfile: tools/docker/edge/ui/Dockerfile
            repo: openems/edge-ui
          - image: backend
            dockerfile: tools/docker/backend/openems/Dockerfile
            repo: openems/backend
          - image: backend-ui
            dockerfile: tools/docker/backend/ui/Dockerfile
            repo: openems/backend-ui
    permissions:
        packages: write
        contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Get cleaned branch name
        id: clean_name
        run: |
          REF_NAME=$(echo "${{ github.ref }}" | sed -e 's/refs\/heads\///' -e 's/refs\/tags\///' -e 's/release\/v//')
          echo "branch=${REF_NAME}-test" >> "$GITHUB_OUTPUT"

      # Re-enable later
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v3
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.repo }}
            ghcr.io/${{ matrix.repo }}
          labels: |
            org.opencontainers.image.authors=OpenEMS.io
            org.opencontainers.image.title=OpenEMS ${{ matrix.image }}
            org.opencontainers.image.vendor=OpenEMS.io

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.2.1
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}